Improves `acronym` scaffold
exercism/clojure pull request #493
Opened 2022-06-08 22:21 UTC by matuella

Same rationale as #490

2022-06-08 22:49 UTC, BTowersCoding requested changes

2022-06-08 22:49 UTC, BTowersCoding commented on exercises/practice/acronym/src/acronym.clj
> +(defn acronym
As long as we're here, it's probably best to remove these comments because at this point they're just adding noise.
```suggestion
(defn acronym
  "Converts phrase to its acronym."
  [phrase]
  )
```

2022-06-09 01:31 UTC, matuella commented
Agreed.

I will try to aim for better docs and more standardized "scaffolds" if I eventually find more things like these.

2022-06-09 01:56 UTC, BTowersCoding commented
It looks like a few lines got repeated:

```
(defn acronym
  "Converts phrase to its acronym."
  [phrase]
  )
  "Converts phrase to its acronym."
  [phrase] ;; <- arglist goes here
  ;; your code goes here
)
```

2022-06-10 16:17 UTC, matuella commented
Sorry, didn't actually see that the suggestion wasn't to be properly committed!

2022-06-10 19:20 UTC, BTowersCoding approved these changes

2022-06-10 19:20 UTC, merged