Reverse string approaches
exercism/clojure pull request #609
Opened 2024-01-20 21:07 UTC by michalporeba

Resolves #601

It's an early draft for early feedback.

2024-01-21 19:32 UTC, michalporeba commented
The approaches are ready for review. @iHiD, @ErikSchierboom

2024-01-22 06:17 UTC, tasxatzial requested changes
@michalporeba Left a quick review.

2024-01-22 06:17 UTC, tasxatzial commented on exercises/practice/reverse-string/.approaches/its-a-sequence/content.md
> +(defn reverse-string [s] ;; <- arglist goes here
Forgotten comment.

2024-01-22 07:45 UTC, ErikSchierboom approved these changes
Great content! Some tiny nits.

2024-01-22 07:45 UTC, ErikSchierboom commented on exercises/practice/reverse-string/.approaches/config.json
> +      "blurb": "Reversing a string a sequence.",
```suggestion
      "blurb": "Reversing a string as sequence.",
```

2024-01-22 07:45 UTC, ErikSchierboom commented on exercises/practice/reverse-string/.approaches/config.json
> +      "title": "It's a sequence",
I would simplify the name a bit:

```suggestion
      "slug": "sequence",
      "title": "Use the fact that a string is also a sequence",
```

2024-01-22 07:45 UTC, ErikSchierboom commented on exercises/practice/reverse-string/.approaches/config.json
> +      "blurb": "Reversing the string recursively.",
```suggestion
      "blurb": "Reverse the string recursively.",
```

2024-01-22 07:45 UTC, ErikSchierboom commented on exercises/practice/reverse-string/.approaches/config.json
> +      "blurb": "Using the StringBuilder class.",
```suggestion
      "blurb": "Use the StringBuilder class.",
```

2024-01-22 13:17 UTC, michalporeba commented on exercises/practice/reverse-string/.approaches/introduction.md
> +[Strings][string] in Clojure are sequences of characters, and there are many ways to reverse a sequence.
Thanks, I'll improve the wording. The key point is that they can be treated as a sequence.

2024-01-22 17:06 UTC, michalporeba commented on exercises/practice/reverse-string/.approaches/config.json
> +      "blurb": "Reversing a string a sequence.",
I'll change it to "Reverse the string as a sequence".

2024-01-22 17:07 UTC, michalporeba commented on exercises/practice/reverse-string/.approaches/its-a-sequence/content.md
> +(defn reverse-string [s] ;; <- arglist goes here
thanks

2024-01-22 17:56 UTC, michalporeba commented
@ErikSchierboom, @tasxatzial, thanks for the feedback. I have made changes to the text. What do you think about it now?

2024-01-22 18:07 UTC, tasxatzial commented on exercises/practice/reverse-string/.approaches/recursion/content.md
> +They can look like the `loop`/`recur` example above, or perhaps use the `letfn` macro as below.
Then you'd have to explain why it overflows and this complicates things even more for no reason, especially when you can simply use `recur` and avoid the overflow. So, if you still want to keep the example, just use `recur` and change the name of the `str` variable since it clashes with the core function `str`. This will make the code look similar to the `loop/recur` approach.

2024-01-22 18:20 UTC, tasxatzial requested changes
one more typo

2024-01-22 18:20 UTC, tasxatzial commented on exercises/practice/reverse-string/.approaches/introduction.md
> +Many core Clojure functions call `seq` on their arguments automatically converting a string into a seqence of characters.
typo in seqence

2024-01-22 18:42 UTC, michalporeba commented on exercises/practice/reverse-string/.approaches/recursion/content.md
> +They can look like the `loop`/`recur` example above, or perhaps use the `letfn` macro as below.
fair point about explaining further. I'll remove this example.

2024-01-22 18:51 UTC, michalporeba commented on exercises/practice/reverse-string/.approaches/introduction.md
> +Many core Clojure functions call `seq` on their arguments automatically converting a string into a seqence of characters.
Thanks for all the proofreading. After way too many months of typing only on my laptop's QWERTY keyboard, I have just switched back to my Moonlander set up with Colemak-DH. Today, typing is a challenge. It will improve in a couple of days.

2024-01-22 19:10 UTC, tasxatzial requested changes
I see that you removed the `letfn` example. I hope you don't mind two final suggestions.

2024-01-22 19:10 UTC, tasxatzial commented on exercises/practice/reverse-string/.approaches/recursion/content.md
> +It is not necessarily bad to use recursion as in these two examples.
```suggestion
It is not necessarily bad to use recursion as shown in the example above.
```

2024-01-22 19:10 UTC, tasxatzial commented on exercises/practice/reverse-string/.approaches/recursion/content.md
> +However, we should remember that strings are immutable, so code like the examples above will be inefficient.
```suggestion
However, we should remember that strings are immutable, so code like the above will be inefficient.
```

2024-01-22 19:12 UTC, tasxatzial commented on exercises/practice/reverse-string/.approaches/introduction.md
> +Many core Clojure functions call `seq` on their arguments automatically converting a string into a seqence of characters.
Don't even think about it. You did a great job. Well done!

2024-01-22 19:41 UTC, michalporeba commented
@ErikSchierboom thanks for approving the PR. I think you will have to click the merge button, as the track's maintainer is currently unavailable. The leap approaches were merged by @iHiD

2024-01-23 07:09 UTC, ErikSchierboom commented
@bobbicodes You around for a review?

2024-01-23 07:10 UTC, merged

2024-01-23 21:38 UTC, iHiD commented
Great work. Thank you! 💙